name: Auto Merge Survey PR

on:
  pull_request_target:
    types: [opened, synchronize]

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-merge:
    runs-on: ubuntu-latest

    steps:
      - name: Auto-merge if only data/responses.json is changed
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const pr = context.payload.pull_request;
            const prNumber = pr.number;
            const owner = context.repo.owner;
            const repo = context.repo.repo;

            const files = await github.paginate(
              github.rest.pulls.listFiles,
              { owner, repo, pull_number: prNumber }
            );

            const filePaths = files.map(file => file.filename);
            const onlyTargetFile = filePaths.length === 1 && filePaths[0] === "data/responses.json";

            if (onlyTargetFile) {
              await github.rest.pulls.merge({
                owner,
                repo,
                pull_number: prNumber,
                merge_method: "squash"
              });
              console.log("✅ 自動マージ成功：responses.json だけが変更されています");
            } else {
              console.log("❌ 自動マージ対象外：他のファイルが含まれています");
              console.log("変更されたファイル:", filePaths);
            }
